version: "2"
services:
  postgresql:
    restart: always
    image: postgres
    networks:
      - sonarnetwork
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  sonar:
    restart: always
    image: goofyk/sonarqube1c
    ports:
      - "9000:9000"
    depends_on:
      - postgresql
    ulimits:
     nofile:
      soft: 65535
      hard: 65535 
    networks:
      - sonarnetwork
    environment:
      - sonar.jdbc.url=jdbc:postgresql://postgresql:5432/sonar
      - sonar.web.javaOpts=-server -Xms256m -Xmx512m -XX:+HeapDumpOnOutOfMemoryError
      - sonar.ce.javaOpts=-Xms256m -Xmx256m -XX:+HeapDumpOnOutOfMemoryError
      - sonar.search.javaOpts=-Xms256m -Xmx256m -XX:+HeapDumpOnOutOfMemoryError
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
networks:
  sonarnetwork:
    driver: bridge
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data: